### PR TITLE
Support GH Actions

### PR DESCRIPTION
**Pull request by alekssamos**
Automatic build of the add-on and loading of the nvda-addon file as a release when creating a tag.

### CODE REVIEW

**Comment by josephsl** [comment]
Hi, can you tell us some details such as use cases so folks reviewing this PR can better understand what’s going on? Thanks.

**Comment by alekssamos** [comment]
Hello.
After the developer has created or updated his add-on, it needs to be assembled and uploaded to the release. This workflow automates the routine process.
The developer simply writes the code, and the installation files of the add-on are automatically collected from it and immediately become available to users.
Some variant of CI/CD.
If Addon Updater or the Spanish community store work with the Github API, then it really turns out to be a real CI/CD.

**Comment by josephsl** [comment]
CC @nvdaes in case you would like to take a look at this, sees similar to your own GitHub Actions workflow. For reference, Add-on Updater does not use GitHub Actions at al. Thanks.

**Comment by nvdaes** [comment]
Hello:

I've taken a look and I see a workflow different to workflows used by me.
Feel free to merge this if you want.
I use an automatic workflow (.yaml file) to make automatic releases
once a week and merge new translations if any. And in my "manual
release" workflow, using workflow-dispatch, I attach the .nvda-addon
file,and also sha256 and signature made with GPG.
I use other workflows to lint, searching for problematic characters
like BOM (created by Mesar Hameed), who help me a lot to learn GitHub
Actions among other things, and to check if some strings have no
comments for translators,using NVDA's source code, which is catched
and should be checked out when new stable releases of NVDA are
published.
https://github.com/nvdaes/nvdaaddonworkflows
And I may make changes to customize actions for add-ons if required.
For example, in cursorLocator I use a workflow for unit testing.
Cheers

2022-10-11 17:54 GMT+02:00, Joseph Lee ***@***.***>:

**Comment by josephsl** [comment]
Hi,

Note that this will cause GitHub Actions for the template to fail, which is expected and we can live with. ne option is renaming the actions folder (.github) to something else, asking developers to rename it to .github once they incorporate this into their own add-on repos.

Thanks.

**Comment by alekssamos** [comment]
there is no failure, look here.

https://github.com/alekssamos/AddonTemplate/releases

**Comment by josephsl** [comment]
Hi, at least on the actual master branch, GitHub says run failed. I think we can live with this as I expect not all authors will adopt GitHub Actions for now. Thanks.

**Comment by alekssamos** [comment]
In any case, this is room for experimentation.

**Comment by josephsl** [comment]
Hi, we can try restricting this to git push –tags for this iteration. Also, some developers release builds (dev and stable) from different branches (I, for one, do so for various reasons). Would you like me to do it provided that I get a weekend off school, would you like to take care of this, or ask someone to take care of it? Please don’t take this question as though I’m not interested in this. Thanks.

**Comment by josephsl** [comment]
Hi,

As a workaround, pushes to main/master branches will be commented out (pull requests will still be built) with the readme stating that people should remove comment when building on main branch. Thanks.

**Pull request merged**
