### PR TITLE
Depend on the correct moFile for a given md file.

### PR DESCRIPTION
**Pull request by derekriemer**
We need the correct title for a given languages translated documentation, which comes from the moFile. However, the previous version of the build script accidentally depended on a variable assigned inside the for loop which was used to assign the languages actual moFile. This loop variable is assigned inside the loop, and not outside it, is overridden on each iteration, and is not persisted anywhere so we cann reference the correct moFile when we later generate the html. This pr fixes that. in this pr, I create a moByLang dictionary, and store the moFile as a value. The key for this moFile is the language code. That way, the html for language KR depends on the moFile for kr, and not the moFile for whatever language was last assigned in the for loop. That way, if the ES languagges po file updates, the dependency system will correctly attribute that Korean is the language we need to regenenrate HTML for. This also undoes the try/except logic that incorrectly hid the real issue, which was the inappropriate refrencing of a for loop variable that may have never been created.

### CODE REVIEW

**Comment by josephsl** [comment]
Comments from @xltechie and others are appreciated. Thanks.

**Comment by XLTechie** [comment]
I am traveling this weekend and probably won't have time to review until Monday. 
Quick take is that I like the idea.

**Comment by derekriemer** [comment]
No worries! Enjoy your travels!

**Comment by derekriemer** [comment]
@XLTechie  can you take a look at this? I'd like to correct the dependency graph here.

**Review by XLTechie — APPROVED** [review]
I'm not in a position to test this right now, but it looks good as far as I can tell, and presumably doesn't break on an untranslated add-on, as discussed under #30.

**Comment by josephsl** [comment]
Hi,

Let's test this in the real world - do revert if things break. Thanks.

**Pull request merged**
