### PR TITLE
Include `pgettext` calls when extracting translatable string literals

### LINKED ISSUE #2: Include `pgettext` calls when extracting translatable string literals
Unlike the NVDA build process, the addon template build process extracts translatable string literals only from calls to `_` (underscore mapped to gettext), ignoring calls to `pgettext` (context-aware translation).

Please consider including calls to `pgettext` as well when extracting translatable string literals.

PR follows.

### PR DESCRIPTION
**Pull request by JulienCochuyt**
Fixes #2

### CODE REVIEW

**Comment by josephsl** [comment]
Hi, I would like to see use cases for pgettext in real-life add-ons, as the template is meant to serve as just that – a template. Thanks.

**Comment by JulienCochuyt** [comment]
> Hi, I would like to see use cases for pgettext in real-life add-ons, as the template is meant to serve as just that – a template. Thanks.

`pgettext` allows translating very short and/or ambiguous terms in an unambiguous manner. Eg, the English word "on" can mean "activated" or "at the upper surface of" or "at the date of" and should then be translated according to the context.

Another common use case of `pgettext` is to set the user-friendly naming of constants.

You can find 200+ occurrences of its use in the NVDA source base.

Furthermore, the `addonHandler` installs it in the global context for use by addons as of nvaccess/nvda#1524, dating back to 2012.3

The change proposed here is 1 line.
As I happened to need supporting it on a project, the motivation is just to spare to the next person facing the same need the hassles of finding where to add it, while enforcing good practice regarding translation.

**Comment by josephsl** [comment]
Hi, I see. Note that this issue (and the workaround that NVDA is using to bring pgettext to the built-in namespace) won’t be necessary anymore in Python 3.8. In the meantime, I’d be happy to include it as part of the add-on template (provided that the community agrees). Thanks.

**Comment by JulienCochuyt** [comment]
@josephsl wrote:
> I’d be happy to include it as part of the add-on template (provided that the community agrees).

Starting to review the great work by @mhameed regarding the use of GitHub Actions to implement a standardized add-on workflow, I stumbled upon [check-against-addon-template](https://github.com/nvdaaddons/l10ntest/blob/master/.github/workflows/check-against-addon-template.yml).
This initiative - which sounds IMHO like a right way to go - leads to my present insistance on merging this very PR.
It is fairly simple, follows NVDA standards, and is crucial towards future publishing of some of our add-ons, most notably [WebAccess](https://github.com/accessolutions/WebAccessForNVDA).

cc @nvdaes

**Comment by nvdaes** [comment]
I think we can continue with this when @NVAccess can work on this and
clarify if they will use their server to built and provide add-on
links to ensure they are download from a known source.
Imo the most complicated part of the process will be how to involve
community reviewers in this process, clarifying standards for
reviewers preserving some kind of flexibility so authors don't feel
discouraged when trying to send add-ons to the store.
For example, simply due to practical matters, since it's not possible
to review each update deppending on the frequency of publications, may
not be possible to follow the model of continuous delivering follow
for add-ons like Windows 10 app essentials or Station Playlist Studio
at least in certain stages. Anyway, certain kind of flexibility for
authors and reviewers maybe good too, and trying to recruit more
reviewers and that we all are aware that the workflow may not be fast
so that some review can be done for each update that involves changes
in code.
Just an opinion.

2020-06-28 11:36 GMT+02:00, Julien Cochuyt <notifications@github.com>:

**Comment by JulienCochuyt** [comment]
@nvdaes, I understand the future process still has to be refined.
Still - as explained in https://github.com/nvdaaddons/AddonTemplate/pull/3#issuecomment-465328168 - this one liner change held off for 16 months simply aims at enabling a feature present in NVDA for 8 years for the sake of good translation practice.
For the record, @jcsteh enabled the support of `pgettext` for add-ons as of nvaccess/nvda#1524.
Our current add-on template simply misses to take advantage of it, without any argument so far for not doing so.

**Comment by josephsl** [comment]
Hi,

While waiting for an official response from NV Access is the ideal situation, we should not forget about the need for this work for benefit of users and translators (and to some extent, add-on authors). Therefore I'm going to merge this work.

Thanks.

**Comment by nvdaes** [comment]
OK, I understand. Just replying you. I am not the maintainer of addon template. I think that add-on authors use different versions of addon template. I will review this PR and with your permision, if I like this, I will use it for my add-ons :) Thanks.

**Comment by josephsl** [comment]
Hi,

Ideally everyone should use the same template version, but getting the community to that step is not easy. At least we can try.

Thanks.

**Comment by nvdaes** [comment]
I agree, but sometimes people like @Abdel792 has fixed things or made
improvements and we haven't a process to include changes in the
official template, so this is not easy since you are the maintainer,
but you may have difficulties to know what include or may not have
time, but I agree, we should try and even we can use the GitHub action
created by @MHameed to check if add-ons use the official template if
it can be maintained accurately.
Cheers

2020-06-28 17:15 GMT+02:00, Joseph Lee <notifications@github.com>:

**Comment by JulienCochuyt** [comment]
@nvdaes wrote:
> with your permision, if I like this, I will use it for my add-ons :) Thanks.

This is licensed under the GPL, you are not only permitted, but very welcome to study, criticize, use, enhance , and redistribute it.

@josephsl, thanks for merging.

IMHO, making this template as usable as can be steps towards its wider adoption and hopefully reduces the burden for add-on authors, sparing their time and energy for what matters more than the build process.

**Comment by nvdaes** [comment]
Thanks Julien. We need to know the process who will be adopted in conjunction with @NVAccess. For example, we can imagine that instead of the sconstruct file used in add-on template with buildvars.py, just manifest are ussed. Or perhaps addon template could be checked out from Github action without addons needing to copy their files and place code itself in the addon subfolder, etc. I think this should be discussed when they take certain control of add-ons. For a long while, we used server scripts created by @Mhameed (originally). Hope you can participate as a reviewer in our community, as well as an author, Julien. I think you have great knowledge. Cheers

Enviado desde mi iPhone

**Pull request merged**
