### PR TITLE
Add workspace configuration for VS Code

### PR DESCRIPTION
**Pull request by nvdaes**
This adds a workspace configuration for authors using VS Code to develop add-ons. Based on [configuration workspace recommended for NVDA](https://github.com/nvaccess/vscode-nvda).

## Features

- Enables accessibility support.
- Ability to autocomplete and analyze code considering NVDA submodules. Requires NVDA's repo with prepared source code in the same root folder than add-on repo.
- When saving a file, a final new line is added to it, and extra new lines are trimmed from the end.
- Indentation uses tabs by default.
- Linting with flake8, using the configuration file of the add-on template (flake8.ini).
- Python interpreter is set to `../nvda/.venv/scripts/python.exe, so that wx (and other packages) can be recognized and suggestedinautocompletion.
- Python, Pylance and extensions for .yaml files can be searched in the recommended extensions for the workspace, to make easy to install them if they are not present.
- undefined variables rule has been disabled to prevent that Pylance shows underscore (_), needed for the translation support, as a problem when pressing `control+shift+m`. flake8 will shows as a problem when other undefined names are encountered.

cc: @Josephsl

### CODE REVIEW

**Comment by nvdaes** [comment]
@josephsl , you can review this when you want. I tested it with some of my add-ons and Windows App Essentials, as well as add-ons by other authors. I didn't find problems in the module opened in WintenApps. For other add-ons, I don't know if we should explain how to disable the linting feature or if it can be easily inferred.
Cheers.

**Comment by nvdaes** [comment]
Seems that something needs to be fixed regarding the creation of the json file, that causes GitHub Actions to fail:

  File "C:\Users\nrm19\Documents\repos\addonTemplate\SConstruct", line 202, in createAddonStoreJson                     
    minimumNVDAVersion = buildVars.addon_info["addon_minimumNVDAVersion"].split(".")                                    
AttributeError: 'NoneType' object has no attribute 'split'

**Comment by josephsl** [comment]
Hi, minimum NVDA version comes from build vars – I wonder if some add-ons are still not defining this… I expect this will impact last tested version flag as well.

**Comment by nvdaes** [comment]
Ah, yes. Then you may set lastTestedVersion in the add-on template to avoid failures of GitHub Actions in future pull requests.

**Comment by josephsl** [comment]
Hi, for now last tested version is set to 0.0.0 via SConstruct since the template is just a template and folks can add these files (and VS config) to their add-on repos. Tanks for catching this bug.

**Comment by nvdaes** [comment]
OK, for now checks of GitHubActions are failing.
Hope you can fix it. Cheers.

**Comment by josephsl** [comment]
Hi,

Merge master branch before continuing with the PR as the attribute error is resolved.

Thanks.

**Comment by josephsl** [comment]
Thanks - merged.

**Comment by nvdaes** [comment]
OK, now all check pass

**Pull request merged**
